language: python
cache: pip
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: [insert username]
  api_key:
    secure: [insert pip key]
  on:
    tags: true
  distributions: sdist bdist_wheel
