name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: Ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.4, 3.5, 3.6.8]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install sphinx
          pip install virtualenv==20.0.1
      - name: Install tox
        if: python-version != 3.4 
        run: pip install tox tox-gh-actions
      - name: Test with tox
        if: python-version != 3.4
        run: |
          tox
          pip install -e .
      - name: Before deploy 
        run: |
          pip install -e .
          pip install --upgrade setuptools
          make docs 
