name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: Ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.4, 3.5, 3.6.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install tox tox-gh-actions 
      - name: Test with tox
        run: |
          tox
      - name: Before deploy 
        run: |
          make docs 